"""Added 'active' field to Client, created relationship between Team and Project

Revision ID: f95ce58093bb
Revises: aa3ce7f85f3d
Create Date: 2025-10-16 21:20:46.889715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95ce58093bb'
down_revision = 'aa3ce7f85f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_projects_team_id_teams'), 'teams', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_projects_team_id_teams'), type_='foreignkey')
        batch_op.drop_column('team_id')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
